package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.CardActive;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface CardActiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_activate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cardActivateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_activate
     *
     * @mbg.generated
     */
    int insert(CardActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_activate
     *
     * @mbg.generated
     */
    int insertSelective(CardActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_activate
     *
     * @mbg.generated
     */
    CardActive selectByPrimaryKey(Long cardActivateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_activate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CardActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_activate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CardActive record);

    List<CardActive> getAllCardActive(CardActive cardActive);

    void getCardNo(Map<String, Object> map);

    int cardActiveCancel(CardActive cardActive);
}