package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.Card;
import com.serviceindeed.yike.yikemo.domain.helper.CardTypeCount;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    Card selectByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Card record);
    int updateByCurrentCardIdSelective(Card card);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Card record);



    List<Card> getAllCards(Card card);

    Integer getCardCounts(CardTypeCount cardTypeCount);

    List<Card> checkIsHaveAlreadyUsedCard(@Param("cardActivateId") Long cardActivateId);

    int cardActiveCancelAndCards(Card card);

    int cardCancel(Card card);


    List<CardTypeCount> selectCardStatus();

    List<CardTypeCount> selectCardTypes();
}