package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.Function;
import com.serviceindeed.yike.yikemo.domain.model.UserFunctionList;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String functionCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int insert(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int insertSelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    Function selectByPrimaryKey(String functionCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Function record);

    List<Function> getAllFunctions();

    /**
     * 根据角色Id查询角色对应功能列表
     * @param roleId
     * @return
     */
    List<UserFunctionList> selectFunctionsByRoleId(Long roleId);
    /**
     * 根据用户Id查询角色对应功能列表
     * @param userId
     * @return
     */
    List<UserFunctionList> selectFunctionsByUserId(Long userId);
}