package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.General;
import com.serviceindeed.yike.yikemo.domain.GeneralKey;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface GeneralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GeneralKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general
     *
     * @mbg.generated
     */
    int insert(General record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general
     *
     * @mbg.generated
     */
    int insertSelective(General record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general
     *
     * @mbg.generated
     */
    General selectByPrimaryKey(GeneralKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(General record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(General record);

    /**
     * 根据keyType查询基础信息
     * @param keyType
     * @return
     */
    List<General> selectByKeyType(String keyType);
}