package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.Grade;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grade
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grade
     *
     * @mbg.generated
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grade
     *
     * @mbg.generated
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grade
     *
     * @mbg.generated
     */
    Grade selectByPrimaryKey(Integer gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grade
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Grade record);

    Grade selectScoreByGradeName(Integer gradeName);

    List<Grade> selectAllGradeName();
}