package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.KnowledgeSystem;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface KnowledgeSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long knowledgeSystemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_system
     *
     * @mbg.generated
     */
    int insert(KnowledgeSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_system
     *
     * @mbg.generated
     */
    int insertSelective(KnowledgeSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_system
     *
     * @mbg.generated
     */
    KnowledgeSystem selectByPrimaryKey(Long knowledgeSystemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KnowledgeSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KnowledgeSystem record);

    /**
     * 查询知识体系列表
     * @param knowledgeSystem
     * @return
     */
    List<KnowledgeSystem> queryKnowledgeSystemList(@Param("knowledgeSystem") KnowledgeSystem knowledgeSystem);
}