package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.Recharge;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long rechargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated
     */
    int insert(Recharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated
     */
    int insertSelective(Recharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated
     */
    Recharge selectByPrimaryKey(Long rechargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Recharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Recharge record);

    List<Recharge> getAllRecharges( Recharge recharge);
}