package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.RoleFunction;
import com.serviceindeed.yike.yikemo.domain.RoleFunctionKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RoleFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolefunction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RoleFunctionKey key);

    int deleteByRoleId(@Param("roleId") Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolefunction
     *
     * @mbg.generated
     */
    int insert(RoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolefunction
     *
     * @mbg.generated
     */
    int insertSelective(RoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolefunction
     *
     * @mbg.generated
     */
    RoleFunction selectByPrimaryKey(RoleFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolefunction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolefunction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleFunction record);

    List<RoleFunction> getFunctionsByRoleId(@Param("roleId") Long roleId);


}