package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.Organization;
import com.serviceindeed.yike.yikemo.domain.School;
import com.serviceindeed.yike.yikemo.domain.Student;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SchoolMapper {

    /**
     * 查询学校信息集合
     * @param school
     * @return
     */
    List<School> querySchoolList(@Param("school")School school);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated
     */
    School selectByPrimaryKey(Long schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(School record);
    /**
     * 校验学校名称是否存在
     * @param school
     * @return
     */
    Integer checkSchoolIsExist(@Param("school") School school);


}