package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.TempClassify;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TempClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_classify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long classifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_classify
     *
     * @mbg.generated
     */
    int insert(TempClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_classify
     *
     * @mbg.generated
     */
    int insertSelective(TempClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_classify
     *
     * @mbg.generated
     */
    TempClassify selectByPrimaryKey(Long classifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_classify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TempClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_classify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TempClassify record);

    List<TempClassify> getTempClassify();
}