package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.TempPraxis;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TempPraxisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_praxis
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long praxisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_praxis
     *
     * @mbg.generated
     */
    int insert(TempPraxis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_praxis
     *
     * @mbg.generated
     */
    int insertSelective(TempPraxis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_praxis
     *
     * @mbg.generated
     */
    TempPraxis selectByPrimaryKey(Long praxisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_praxis
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TempPraxis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_praxis
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TempPraxis record);

    List<TempPraxis> getAllPraxis(TempPraxis tempPraxis);
}