package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.UserFunction;
import com.serviceindeed.yike.yikemo.domain.UserFunctionKey;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Service;

import java.util.List;
@Mapper
public interface UserFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userfunction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(UserFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userfunction
     *
     * @mbg.generated
     */
    int insert(UserFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userfunction
     *
     * @mbg.generated
     */
    int insertSelective(UserFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userfunction
     *
     * @mbg.generated
     */
    UserFunction selectByPrimaryKey(UserFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userfunction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userfunction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserFunction record);

    List<UserFunction> getFunctionsByUserId(Long userId);


    int deleteByUserId(Long userId);
}