package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class CardActive  extends Columns implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.CARD_ACTIVATE_ID
     *
     * @mbg.generated
     */
    private Long cardActivateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.ORG_ID
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.SCHOOL_ID
     *
     * @mbg.generated
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.RECOMMAND_TEACHER
     *
     * @mbg.generated
     */
    private String recommandTeacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.CARD_TYPE
     *
     * @mbg.generated
     */
    private Long rechargeType;

    private String cardPassword;

    public String getCardPassword() {
        return cardPassword;
    }

    public void setCardPassword(String cardPassword) {
        this.cardPassword = cardPassword;
    }

    public Long getRechargeType() {
        return rechargeType;
    }

    public void setRechargeType(Long rechargeType) {
        this.rechargeType = rechargeType;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.STAND_PRICE
     *
     * @mbg.generated
     */
    private Double standardPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.MIN_PRICE
     *
     * @mbg.generated
     */
    private Double minPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.SALES_PRICE
     *
     * @mbg.generated
     */
    private Double salesPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.CARD_NUMBER
     *
     * @mbg.generated
     */
    private Integer cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.AMOUNT
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.CARD_CHANNEL
     *
     * @mbg.generated
     */
    private String cardChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.UPDATE_BY
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    private String updatePlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_activate.UPDATE_VERSION
     *
     * @mbg.generated
     */
    private String updateVersion;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endDate;

    private String schoolName;
    private String orgName;
    private String rechargeTypeName;
    private String userName;
    private String statusValue;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getStatusValue() {
        return statusValue;
    }

    public void setStatusValue(String statusValue) {
        this.statusValue = statusValue;
    }

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getRechargeTypeName() {
        return rechargeTypeName;
    }

    public void setRechargeTypeName(String rechargeTypeName) {
        this.rechargeTypeName = rechargeTypeName;
    }

    public Date getStartDate() {

        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.CARD_ACTIVATE_ID
     *
     * @return the value of t_card_activate.CARD_ACTIVATE_ID
     *
     * @mbg.generated
     */
    public Long getCardActivateId() {
        return cardActivateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.CARD_ACTIVATE_ID
     *
     * @param cardActivateId the value for t_card_activate.CARD_ACTIVATE_ID
     *
     * @mbg.generated
     */
    public void setCardActivateId(Long cardActivateId) {
        this.cardActivateId = cardActivateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.ORG_ID
     *
     * @return the value of t_card_activate.ORG_ID
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.ORG_ID
     *
     * @param orgId the value for t_card_activate.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.SCHOOL_ID
     *
     * @return the value of t_card_activate.SCHOOL_ID
     *
     * @mbg.generated
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.SCHOOL_ID
     *
     * @param schoolId the value for t_card_activate.SCHOOL_ID
     *
     * @mbg.generated
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.RECOMMAND_TEACHER
     *
     * @return the value of t_card_activate.RECOMMAND_TEACHER
     *
     * @mbg.generated
     */
    public String getRecommandTeacher() {
        return recommandTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.RECOMMAND_TEACHER
     *
     * @param recommandTeacher the value for t_card_activate.RECOMMAND_TEACHER
     *
     * @mbg.generated
     */
    public void setRecommandTeacher(String recommandTeacher) {
        this.recommandTeacher = recommandTeacher == null ? null : recommandTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.CARD_TYPE
     *
     * @return the value of t_card_activate.CARD_TYPE
     *
     * @mbg.generated
     */
     /*public String getCardType() {
        return cardType;
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.CARD_TYPE
     *
     * @param cardType the value for t_card_activate.CARD_TYPE
     *
     * @mbg.generated
     */
  /*  public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.STAND_PRICE
     *
     * @return the value of t_card_activate.STAND_PRICE
     *
     * @mbg.generated
     */
    public Double getStandardPrice() {
        return standardPrice;
    }

    public void setStandardPrice(Double standardPrice) {
        this.standardPrice = standardPrice;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.STAND_PRICE
     *
     * @param standardPrice the value for t_card_activate.STAND_PRICE
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.MIN_PRICE
     *
     * @return the value of t_card_activate.MIN_PRICE
     *
     * @mbg.generated
     */
    public Double getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.MIN_PRICE
     *
     * @param minPrice the value for t_card_activate.MIN_PRICE
     *
     * @mbg.generated
     */
    public void setMinPrice(Double minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.SALES_PRICE
     *
     * @return the value of t_card_activate.SALES_PRICE
     *
     * @mbg.generated
     */
    public Double getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.SALES_PRICE
     *
     * @param salesPrice the value for t_card_activate.SALES_PRICE
     *
     * @mbg.generated
     */
    public void setSalesPrice(Double salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.CARD_NUMBER
     *
     * @return the value of t_card_activate.CARD_NUMBER
     *
     * @mbg.generated
     */
    public Integer getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.CARD_NUMBER
     *
     * @param cardNumber the value for t_card_activate.CARD_NUMBER
     *
     * @mbg.generated
     */
    public void setCardNumber(Integer cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.AMOUNT
     *
     * @return the value of t_card_activate.AMOUNT
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.AMOUNT
     *
     * @param amount the value for t_card_activate.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.CARD_CHANNEL
     *
     * @return the value of t_card_activate.CARD_CHANNEL
     *
     * @mbg.generated
     */
    public String getCardChannel() {
        return cardChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.CARD_CHANNEL
     *
     * @param cardChannel the value for t_card_activate.CARD_CHANNEL
     *
     * @mbg.generated
     */
    public void setCardChannel(String cardChannel) {
        this.cardChannel = cardChannel == null ? null : cardChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.STATUS
     *
     * @return the value of t_card_activate.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.STATUS
     *
     * @param status the value for t_card_activate.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.REMARK
     *
     * @return the value of t_card_activate.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.REMARK
     *
     * @param remark the value for t_card_activate.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.CREATE_BY
     *
     * @return the value of t_card_activate.CREATE_BY
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.CREATE_BY
     *
     * @param createBy the value for t_card_activate.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.CREATE_DATE
     *
     * @return the value of t_card_activate.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.CREATE_DATE
     *
     * @param createDate the value for t_card_activate.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.CREATE_PLATFORM
     *
     * @return the value of t_card_activate.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_card_activate.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.CREATE_VERSION
     *
     * @return the value of t_card_activate.CREATE_VERSION
     *
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.CREATE_VERSION
     *
     * @param createVersion the value for t_card_activate.CREATE_VERSION
     *
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.UPDATE_BY
     *
     * @return the value of t_card_activate.UPDATE_BY
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.UPDATE_BY
     *
     * @param updateBy the value for t_card_activate.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.UPDATE_DATE
     *
     * @return the value of t_card_activate.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.UPDATE_DATE
     *
     * @param updateDate the value for t_card_activate.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.UPDATE_PLATFORM
     *
     * @return the value of t_card_activate.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getUpdatePlatform() {
        return updatePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.UPDATE_PLATFORM
     *
     * @param updatePlatform the value for t_card_activate.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setUpdatePlatform(String updatePlatform) {
        this.updatePlatform = updatePlatform == null ? null : updatePlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_activate.UPDATE_VERSION
     *
     * @return the value of t_card_activate.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_activate.UPDATE_VERSION
     *
     * @param updateVersion the value for t_card_activate.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }
}