package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;

public class Function  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.FUNCTION_CODE
     *
     * @mbg.generated
     */
    private String functionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.FUNCTION_NAME
     *
     * @mbg.generated
     */
    private String functionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.PARENT_CODE
     *
     * @mbg.generated
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.LEVEL
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.IS_ENABLE
     *
     * @mbg.generated
     */
    private String isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.SORT_ORDER
     *
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.REMARK
     *
     * @mbg.generated
     */
    private String remark;
    /**
     * 所属父名称
     */
    private String parentName;
    private Long userId;
    private Long roleId;
    private String url;
    private String style;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.FUNCTION_CODE
     *
     * @return the value of t_function.FUNCTION_CODE
     *
     * @mbg.generated
     */
    public String getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.FUNCTION_CODE
     *
     * @param functionCode the value for t_function.FUNCTION_CODE
     *
     * @mbg.generated
     */
    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode == null ? null : functionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.FUNCTION_NAME
     *
     * @return the value of t_function.FUNCTION_NAME
     *
     * @mbg.generated
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.FUNCTION_NAME
     *
     * @param functionName the value for t_function.FUNCTION_NAME
     *
     * @mbg.generated
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName == null ? null : functionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.PARENT_CODE
     *
     * @return the value of t_function.PARENT_CODE
     *
     * @mbg.generated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.PARENT_CODE
     *
     * @param parentCode the value for t_function.PARENT_CODE
     *
     * @mbg.generated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.LEVEL
     *
     * @return the value of t_function.LEVEL
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.LEVEL
     *
     * @param level the value for t_function.LEVEL
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.IS_ENABLE
     *
     * @return the value of t_function.IS_ENABLE
     *
     * @mbg.generated
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.IS_ENABLE
     *
     * @param isEnable the value for t_function.IS_ENABLE
     *
     * @mbg.generated
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.SORT_ORDER
     *
     * @return the value of t_function.SORT_ORDER
     *
     * @mbg.generated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.SORT_ORDER
     *
     * @param sortOrder the value for t_function.SORT_ORDER
     *
     * @mbg.generated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.REMARK
     *
     * @return the value of t_function.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.REMARK
     *
     * @param remark the value for t_function.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String style) {
        this.style = style;
    }
}