package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;

public class GeneralKey extends Columns {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general.KEY_TYPE
     *
     * @mbg.generated
     */
    private String keyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general.KEY_CODE
     *
     * @mbg.generated
     */
    private String keyCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general.KEY_TYPE
     *
     * @return the value of t_general.KEY_TYPE
     *
     * @mbg.generated
     */
    public String getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general.KEY_TYPE
     *
     * @param keyType the value for t_general.KEY_TYPE
     *
     * @mbg.generated
     */
    public void setKeyType(String keyType) {
        this.keyType = keyType == null ? null : keyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general.KEY_CODE
     *
     * @return the value of t_general.KEY_CODE
     *
     * @mbg.generated
     */
    public String getKeyCode() {
        return keyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general.KEY_CODE
     *
     * @param keyCode the value for t_general.KEY_CODE
     *
     * @mbg.generated
     */
    public void setKeyCode(String keyCode) {
        this.keyCode = keyCode == null ? null : keyCode.trim();
    }
}