package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;
import org.springframework.web.multipart.MultipartFile;

import java.io.Serializable;
import java.util.Date;

public class KnowledgePointDetail extends Columns implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.KNOWLEDGE_POINT_DETAIL_ID
     *
     * @mbg.generated
     */
    private Long knowledgePointDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.ORG_ID
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.POINT_ID
     *
     * @mbg.generated
     */
    private Long pointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.DETAIL_DESC
     *
     * @mbg.generated
     */
    private String detailDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.SGF_PATH
     *
     * @mbg.generated
     */
    private String sgfPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.UPDATE_BY
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    private String updatePlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point_detail.UPDATE_VERSION
     *
     * @mbg.generated
     */
    private String updateVersion;
    /**
     * sgf文件
     */
    private MultipartFile sgfFile;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.KNOWLEDGE_POINT_DETAIL_ID
     *
     * @return the value of t_knowledge_point_detail.KNOWLEDGE_POINT_DETAIL_ID
     *
     * @mbg.generated
     */
    public Long getKnowledgePointDetailId() {
        return knowledgePointDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.KNOWLEDGE_POINT_DETAIL_ID
     *
     * @param knowledgePointDetailId the value for t_knowledge_point_detail.KNOWLEDGE_POINT_DETAIL_ID
     *
     * @mbg.generated
     */
    public void setKnowledgePointDetailId(Long knowledgePointDetailId) {
        this.knowledgePointDetailId = knowledgePointDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.ORG_ID
     *
     * @return the value of t_knowledge_point_detail.ORG_ID
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.ORG_ID
     *
     * @param orgId the value for t_knowledge_point_detail.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.POINT_ID
     *
     * @return the value of t_knowledge_point_detail.POINT_ID
     *
     * @mbg.generated
     */
    public Long getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.POINT_ID
     *
     * @param pointId the value for t_knowledge_point_detail.POINT_ID
     *
     * @mbg.generated
     */
    public void setPointId(Long pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.DETAIL_DESC
     *
     * @return the value of t_knowledge_point_detail.DETAIL_DESC
     *
     * @mbg.generated
     */
    public String getDetailDesc() {
        return detailDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.DETAIL_DESC
     *
     * @param detailDesc the value for t_knowledge_point_detail.DETAIL_DESC
     *
     * @mbg.generated
     */
    public void setDetailDesc(String detailDesc) {
        this.detailDesc = detailDesc == null ? null : detailDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.SGF_PATH
     *
     * @return the value of t_knowledge_point_detail.SGF_PATH
     *
     * @mbg.generated
     */
    public String getSgfPath() {
        return sgfPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.SGF_PATH
     *
     * @param sgfPath the value for t_knowledge_point_detail.SGF_PATH
     *
     * @mbg.generated
     */
    public void setSgfPath(String sgfPath) {
        this.sgfPath = sgfPath == null ? null : sgfPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.CREATE_BY
     *
     * @return the value of t_knowledge_point_detail.CREATE_BY
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.CREATE_BY
     *
     * @param createBy the value for t_knowledge_point_detail.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.CREATE_DATE
     *
     * @return the value of t_knowledge_point_detail.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.CREATE_DATE
     *
     * @param createDate the value for t_knowledge_point_detail.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.CREATE_PLATFORM
     *
     * @return the value of t_knowledge_point_detail.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_knowledge_point_detail.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.CREATE_VERSION
     *
     * @return the value of t_knowledge_point_detail.CREATE_VERSION
     *
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.CREATE_VERSION
     *
     * @param createVersion the value for t_knowledge_point_detail.CREATE_VERSION
     *
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.UPDATE_BY
     *
     * @return the value of t_knowledge_point_detail.UPDATE_BY
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.UPDATE_BY
     *
     * @param updateBy the value for t_knowledge_point_detail.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.UPDATE_DATE
     *
     * @return the value of t_knowledge_point_detail.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.UPDATE_DATE
     *
     * @param updateDate the value for t_knowledge_point_detail.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.UPDATE_PLATFORM
     *
     * @return the value of t_knowledge_point_detail.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getUpdatePlatform() {
        return updatePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.UPDATE_PLATFORM
     *
     * @param updatePlatform the value for t_knowledge_point_detail.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setUpdatePlatform(String updatePlatform) {
        this.updatePlatform = updatePlatform == null ? null : updatePlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point_detail.UPDATE_VERSION
     *
     * @return the value of t_knowledge_point_detail.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point_detail.UPDATE_VERSION
     *
     * @param updateVersion the value for t_knowledge_point_detail.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }

    public MultipartFile getSgfFile() {
        return sgfFile;
    }

    public void setSgfFile(MultipartFile sgfFile) {
        this.sgfFile = sgfFile;
    }
}