package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;

import java.io.Serializable;
import java.util.Date;

public class KnowledgeSystem extends Columns implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.KNOWLEDGE_SYSTEM_ID
     *
     * @mbg.generated
     */
    private Long knowledgeSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.ORG_ID
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.PARENT_SYSTEM_ID
     *
     * @mbg.generated
     */
    private Long parentSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.SYSTEM_NAME
     *
     * @mbg.generated
     */
    private String systemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.SYSTEM_DESC
     *
     * @mbg.generated
     */
    private String systemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.SYSTEM_LEVEL
     *
     * @mbg.generated
     */
    private Integer systemLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.SYSTEM_TYPE
     *
     * @mbg.generated
     */
    private String systemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.IS_ENABLE
     *
     * @mbg.generated
     */
    private String isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.UPDATE_BY
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    private String updatePlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_system.UPDATE_VERSION
     *
     * @mbg.generated
     */
    private String updateVersion;

    private String parentSystemName;
    private String systemTypeLabel;
    private String isEnableLabel;
    private String createByName;
    private String updateByName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.KNOWLEDGE_SYSTEM_ID
     *
     * @return the value of t_knowledge_system.KNOWLEDGE_SYSTEM_ID
     * @mbg.generated
     */
    public Long getKnowledgeSystemId() {
        return knowledgeSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.KNOWLEDGE_SYSTEM_ID
     *
     * @param knowledgeSystemId the value for t_knowledge_system.KNOWLEDGE_SYSTEM_ID
     * @mbg.generated
     */
    public void setKnowledgeSystemId(Long knowledgeSystemId) {
        this.knowledgeSystemId = knowledgeSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.ORG_ID
     *
     * @return the value of t_knowledge_system.ORG_ID
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.ORG_ID
     *
     * @param orgId the value for t_knowledge_system.ORG_ID
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.PARENT_SYSTEM_ID
     *
     * @return the value of t_knowledge_system.PARENT_SYSTEM_ID
     * @mbg.generated
     */
    public Long getParentSystemId() {
        return parentSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.PARENT_SYSTEM_ID
     *
     * @param parentSystemId the value for t_knowledge_system.PARENT_SYSTEM_ID
     * @mbg.generated
     */
    public void setParentSystemId(Long parentSystemId) {
        this.parentSystemId = parentSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.SYSTEM_NAME
     *
     * @return the value of t_knowledge_system.SYSTEM_NAME
     * @mbg.generated
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.SYSTEM_NAME
     *
     * @param systemName the value for t_knowledge_system.SYSTEM_NAME
     * @mbg.generated
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.SYSTEM_DESC
     *
     * @return the value of t_knowledge_system.SYSTEM_DESC
     * @mbg.generated
     */
    public String getSystemDesc() {
        return systemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.SYSTEM_DESC
     *
     * @param systemDesc the value for t_knowledge_system.SYSTEM_DESC
     * @mbg.generated
     */
    public void setSystemDesc(String systemDesc) {
        this.systemDesc = systemDesc == null ? null : systemDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.SYSTEM_LEVEL
     *
     * @return the value of t_knowledge_system.SYSTEM_LEVEL
     * @mbg.generated
     */
    public Integer getSystemLevel() {
        return systemLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.SYSTEM_LEVEL
     *
     * @param systemLevel the value for t_knowledge_system.SYSTEM_LEVEL
     * @mbg.generated
     */
    public void setSystemLevel(Integer systemLevel) {
        this.systemLevel = systemLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.SYSTEM_TYPE
     *
     * @return the value of t_knowledge_system.SYSTEM_TYPE
     * @mbg.generated
     */
    public String getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.SYSTEM_TYPE
     *
     * @param systemType the value for t_knowledge_system.SYSTEM_TYPE
     * @mbg.generated
     */
    public void setSystemType(String systemType) {
        this.systemType = systemType == null ? null : systemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.IS_ENABLE
     *
     * @return the value of t_knowledge_system.IS_ENABLE
     * @mbg.generated
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.IS_ENABLE
     *
     * @param isEnable the value for t_knowledge_system.IS_ENABLE
     * @mbg.generated
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.CREATE_BY
     *
     * @return the value of t_knowledge_system.CREATE_BY
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.CREATE_BY
     *
     * @param createBy the value for t_knowledge_system.CREATE_BY
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.CREATE_DATE
     *
     * @return the value of t_knowledge_system.CREATE_DATE
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.CREATE_DATE
     *
     * @param createDate the value for t_knowledge_system.CREATE_DATE
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.CREATE_PLATFORM
     *
     * @return the value of t_knowledge_system.CREATE_PLATFORM
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_knowledge_system.CREATE_PLATFORM
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.CREATE_VERSION
     *
     * @return the value of t_knowledge_system.CREATE_VERSION
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.CREATE_VERSION
     *
     * @param createVersion the value for t_knowledge_system.CREATE_VERSION
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.UPDATE_BY
     *
     * @return the value of t_knowledge_system.UPDATE_BY
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.UPDATE_BY
     *
     * @param updateBy the value for t_knowledge_system.UPDATE_BY
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.UPDATE_DATE
     *
     * @return the value of t_knowledge_system.UPDATE_DATE
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.UPDATE_DATE
     *
     * @param updateDate the value for t_knowledge_system.UPDATE_DATE
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.UPDATE_PLATFORM
     *
     * @return the value of t_knowledge_system.UPDATE_PLATFORM
     * @mbg.generated
     */
    public String getUpdatePlatform() {
        return updatePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.UPDATE_PLATFORM
     *
     * @param updatePlatform the value for t_knowledge_system.UPDATE_PLATFORM
     * @mbg.generated
     */
    public void setUpdatePlatform(String updatePlatform) {
        this.updatePlatform = updatePlatform == null ? null : updatePlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_system.UPDATE_VERSION
     *
     * @return the value of t_knowledge_system.UPDATE_VERSION
     * @mbg.generated
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_system.UPDATE_VERSION
     *
     * @param updateVersion the value for t_knowledge_system.UPDATE_VERSION
     * @mbg.generated
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }

    public String getParentSystemName() {
        return parentSystemName;
    }
    public void setParentSystemName(String parentSystemName) {
        this.parentSystemName = parentSystemName;
    }

    public String getSystemTypeLabel() {
        return systemTypeLabel;
    }

    public void setSystemTypeLabel(String systemTypeLabel) {
        this.systemTypeLabel = systemTypeLabel;
    }

    public String getIsEnableLabel() {
        return isEnableLabel;
    }

    public void setIsEnableLabel(String isEnableLabel) {
        this.isEnableLabel = isEnableLabel;
    }

    public String getCreateByName() {
        return createByName;
    }

    public void setCreateByName(String createByName) {
        this.createByName = createByName;
    }

    public String getUpdateByName() {
        return updateByName;
    }

    public void setUpdateByName(String updateByName) {
        this.updateByName = updateByName;
    }
}