package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;
import org.springframework.web.multipart.MultipartFile;

import java.io.Serializable;
import java.util.Date;

public class KnowledgePoint extends Columns implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.KNOWLEDGE_POINT_ID
     *
     * @mbg.generated
     */
    private Long knowledgePointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.ORG_ID
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.SYSTEM_ID
     *
     * @mbg.generated
     */
    private Long systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.POINT_NAME
     *
     * @mbg.generated
     */
    private String pointName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.POINT_DESC
     *
     * @mbg.generated
     */
    private String pointDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.MIN_DAN
     *
     * @mbg.generated
     */
    private Integer minDan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.MAX_DAN
     *
     * @mbg.generated
     */
    private Integer maxDan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.IS_FREE
     *
     * @mbg.generated
     */
    private String isFree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.POINT_TYPE
     *
     * @mbg.generated
     */
    private String pointType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.UPDATE_BY
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    private String updatePlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge_point.UPDATE_VERSION
     *
     * @mbg.generated
     */
    private String updateVersion;
    private String systemName;
    private Long parentSystemId;
    private String parentSystemName;
    private Integer systemLevel;
    private String systemLevelLabel;

    private String orgName;
    private String minDanValue;
    private String maxDanValue;
    private String createByName;
    private String isFreeLabel;
    private String statusLabel;
    private String pointTypeLabel;

    public Long getParentSystemId() {
        return parentSystemId;
    }

    public void setParentSystemId(Long parentSystemId) {
        this.parentSystemId = parentSystemId;
    }

    public String getIsFreeLabel() {
        return isFreeLabel;
    }

    public void setIsFreeLabel(String isFreeLabel) {
        this.isFreeLabel = isFreeLabel;
    }

    public String getStatusLabel() {
        return statusLabel;
    }

    public void setStatusLabel(String statusLabel) {
        this.statusLabel = statusLabel;
    }

    public String getPointTypeLabel() {
        return pointTypeLabel;
    }

    public void setPointTypeLabel(String pointTypeLabel) {
        this.pointTypeLabel = pointTypeLabel;
    }

    public String getParentSystemName() {
        return parentSystemName;
    }

    public void setParentSystemName(String parentSystemName) {
        this.parentSystemName = parentSystemName;
    }

    public String getSystemName() {
        return systemName;
    }

    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }

    public Integer getSystemLevel() {
        return systemLevel;
    }

    public void setSystemLevel(Integer systemLevel) {
        this.systemLevel = systemLevel;
    }

    public String getSystemLevelLabel() {
        return systemLevelLabel;
    }

    public void setSystemLevelLabel(String systemLevelLabel) {
        this.systemLevelLabel = systemLevelLabel;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getMinDanValue() {
        return minDanValue;
    }

    public void setMinDanValue(String minDanValue) {
        this.minDanValue = minDanValue;
    }

    public String getMaxDanValue() {
        return maxDanValue;
    }

    public void setMaxDanValue(String maxDanValue) {
        this.maxDanValue = maxDanValue;
    }

    public String getCreateByName() {
        return createByName;
    }

    public void setCreateByName(String createByName) {
        this.createByName = createByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.KNOWLEDGE_POINT_ID
     *
     * @return the value of t_knowledge_point.KNOWLEDGE_POINT_ID
     *
     * @mbg.generated
     */
    public Long getKnowledgePointId() {
        return knowledgePointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.KNOWLEDGE_POINT_ID
     *
     * @param knowledgePointId the value for t_knowledge_point.KNOWLEDGE_POINT_ID
     *
     * @mbg.generated
     */
    public void setKnowledgePointId(Long knowledgePointId) {
        this.knowledgePointId = knowledgePointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.ORG_ID
     *
     * @return the value of t_knowledge_point.ORG_ID
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.ORG_ID
     *
     * @param orgId the value for t_knowledge_point.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.SYSTEM_ID
     *
     * @return the value of t_knowledge_point.SYSTEM_ID
     *
     * @mbg.generated
     */
    public Long getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.SYSTEM_ID
     *
     * @param systemId the value for t_knowledge_point.SYSTEM_ID
     *
     * @mbg.generated
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.POINT_NAME
     *
     * @return the value of t_knowledge_point.POINT_NAME
     *
     * @mbg.generated
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.POINT_NAME
     *
     * @param pointName the value for t_knowledge_point.POINT_NAME
     *
     * @mbg.generated
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.POINT_DESC
     *
     * @return the value of t_knowledge_point.POINT_DESC
     *
     * @mbg.generated
     */
    public String getPointDesc() {
        return pointDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.POINT_DESC
     *
     * @param pointDesc the value for t_knowledge_point.POINT_DESC
     *
     * @mbg.generated
     */
    public void setPointDesc(String pointDesc) {
        this.pointDesc = pointDesc == null ? null : pointDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.MIN_DAN
     *
     * @return the value of t_knowledge_point.MIN_DAN
     *
     * @mbg.generated
     */
    public Integer getMinDan() {
        return minDan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.MIN_DAN
     *
     * @param minDan the value for t_knowledge_point.MIN_DAN
     *
     * @mbg.generated
     */
    public void setMinDan(Integer minDan) {
        this.minDan = minDan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.MAX_DAN
     *
     * @return the value of t_knowledge_point.MAX_DAN
     *
     * @mbg.generated
     */
    public Integer getMaxDan() {
        return maxDan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.MAX_DAN
     *
     * @param maxDan the value for t_knowledge_point.MAX_DAN
     *
     * @mbg.generated
     */
    public void setMaxDan(Integer maxDan) {
        this.maxDan = maxDan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.IS_FREE
     *
     * @return the value of t_knowledge_point.IS_FREE
     *
     * @mbg.generated
     */
    public String getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.IS_FREE
     *
     * @param isFree the value for t_knowledge_point.IS_FREE
     *
     * @mbg.generated
     */
    public void setIsFree(String isFree) {
        this.isFree = isFree == null ? null : isFree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.POINT_TYPE
     *
     * @return the value of t_knowledge_point.POINT_TYPE
     *
     * @mbg.generated
     */
    public String getPointType() {
        return pointType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.POINT_TYPE
     *
     * @param pointType the value for t_knowledge_point.POINT_TYPE
     *
     * @mbg.generated
     */
    public void setPointType(String pointType) {
        this.pointType = pointType == null ? null : pointType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.STATUS
     *
     * @return the value of t_knowledge_point.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.STATUS
     *
     * @param status the value for t_knowledge_point.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.CREATE_BY
     *
     * @return the value of t_knowledge_point.CREATE_BY
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.CREATE_BY
     *
     * @param createBy the value for t_knowledge_point.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.CREATE_DATE
     *
     * @return the value of t_knowledge_point.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.CREATE_DATE
     *
     * @param createDate the value for t_knowledge_point.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.CREATE_PLATFORM
     *
     * @return the value of t_knowledge_point.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_knowledge_point.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.CREATE_VERSION
     *
     * @return the value of t_knowledge_point.CREATE_VERSION
     *
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.CREATE_VERSION
     *
     * @param createVersion the value for t_knowledge_point.CREATE_VERSION
     *
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.UPDATE_BY
     *
     * @return the value of t_knowledge_point.UPDATE_BY
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.UPDATE_BY
     *
     * @param updateBy the value for t_knowledge_point.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.UPDATE_DATE
     *
     * @return the value of t_knowledge_point.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.UPDATE_DATE
     *
     * @param updateDate the value for t_knowledge_point.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.UPDATE_PLATFORM
     *
     * @return the value of t_knowledge_point.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getUpdatePlatform() {
        return updatePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.UPDATE_PLATFORM
     *
     * @param updatePlatform the value for t_knowledge_point.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setUpdatePlatform(String updatePlatform) {
        this.updatePlatform = updatePlatform == null ? null : updatePlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge_point.UPDATE_VERSION
     *
     * @return the value of t_knowledge_point.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge_point.UPDATE_VERSION
     *
     * @param updateVersion the value for t_knowledge_point.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }
}