package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;
import org.springframework.web.multipart.MultipartFile;

import java.io.Serializable;
import java.util.Date;

public class Organization extends Columns implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.ORG_ID
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.ORG_NAME
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.ORG_ABBRNAME
     *
     * @mbg.generated
     */
    private String orgAbbrname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.ORG_ADDRESS
     *
     * @mbg.generated
     */
    private String orgAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.ORG_CONTACT
     *
     * @mbg.generated
     */
    private String orgContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.ORG_TEL
     *
     * @mbg.generated
     */
    private String orgTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.ORG_WEBSITE
     *
     * @mbg.generated
     */
    private String orgWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.ORG_LOGO
     *
     * @mbg.generated
     */
    private String orgLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.APPLY_BY
     *
     * @mbg.generated
     */
    private String applyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.APPLY_DATE
     *
     * @mbg.generated
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.AUDIT_BY
     *
     * @mbg.generated
     */
    private Long auditBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.AUDIT_DATE
     *
     * @mbg.generated
     */
    private Date auditDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.UPDATE_BY
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    private String updatePlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.UPDATE_VERSION
     *
     * @mbg.generated
     */
    private String updateVersion;


    /**
     * 审核人
     */
    private String auditName;
    /**
     * 创建人
     */
    private String createName;
    /**
     * 修改人
     */
    private String updateName;
    /**
     * 状态描述
     */
    private String statusLabel;
    /**
     * 学校数量
     */
    private Long count;
    /**
     * 是否创建学校
     */
    private String isCreateSchool;
    /**
     * 机构Logo文件
     */
    private MultipartFile fileOrgLogo;
    /**
     * 是否删除已上传文件
     */
    private Boolean delImage;




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.ORG_ID
     *
     * @return the value of t_organization.ORG_ID
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.ORG_ID
     *
     * @param orgId the value for t_organization.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.ORG_NAME
     *
     * @return the value of t_organization.ORG_NAME
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.ORG_NAME
     *
     * @param orgName the value for t_organization.ORG_NAME
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.ORG_ABBRNAME
     *
     * @return the value of t_organization.ORG_ABBRNAME
     *
     * @mbg.generated
     */
    public String getOrgAbbrname() {
        return orgAbbrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.ORG_ABBRNAME
     *
     * @param orgAbbrname the value for t_organization.ORG_ABBRNAME
     *
     * @mbg.generated
     */
    public void setOrgAbbrname(String orgAbbrname) {
        this.orgAbbrname = orgAbbrname == null ? null : orgAbbrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.ORG_ADDRESS
     *
     * @return the value of t_organization.ORG_ADDRESS
     *
     * @mbg.generated
     */
    public String getOrgAddress() {
        return orgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.ORG_ADDRESS
     *
     * @param orgAddress the value for t_organization.ORG_ADDRESS
     *
     * @mbg.generated
     */
    public void setOrgAddress(String orgAddress) {
        this.orgAddress = orgAddress == null ? null : orgAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.ORG_CONTACT
     *
     * @return the value of t_organization.ORG_CONTACT
     *
     * @mbg.generated
     */
    public String getOrgContact() {
        return orgContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.ORG_CONTACT
     *
     * @param orgContact the value for t_organization.ORG_CONTACT
     *
     * @mbg.generated
     */
    public void setOrgContact(String orgContact) {
        this.orgContact = orgContact == null ? null : orgContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.ORG_TEL
     *
     * @return the value of t_organization.ORG_TEL
     *
     * @mbg.generated
     */
    public String getOrgTel() {
        return orgTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.ORG_TEL
     *
     * @param orgTel the value for t_organization.ORG_TEL
     *
     * @mbg.generated
     */
    public void setOrgTel(String orgTel) {
        this.orgTel = orgTel == null ? null : orgTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.ORG_WEBSITE
     *
     * @return the value of t_organization.ORG_WEBSITE
     *
     * @mbg.generated
     */
    public String getOrgWebsite() {
        return orgWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.ORG_WEBSITE
     *
     * @param orgWebsite the value for t_organization.ORG_WEBSITE
     *
     * @mbg.generated
     */
    public void setOrgWebsite(String orgWebsite) {
        this.orgWebsite = orgWebsite == null ? null : orgWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.ORG_LOGO
     *
     * @return the value of t_organization.ORG_LOGO
     *
     * @mbg.generated
     */
    public String getOrgLogo() {
        return orgLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.ORG_LOGO
     *
     * @param orgLogo the value for t_organization.ORG_LOGO
     *
     * @mbg.generated
     */
    public void setOrgLogo(String orgLogo) {
        this.orgLogo = orgLogo == null ? null : orgLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.APPLY_BY
     *
     * @return the value of t_organization.APPLY_BY
     *
     * @mbg.generated
     */
    public String getApplyBy() {
        return applyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.APPLY_BY
     *
     * @param applyBy the value for t_organization.APPLY_BY
     *
     * @mbg.generated
     */
    public void setApplyBy(String applyBy) {
        this.applyBy = applyBy == null ? null : applyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.APPLY_DATE
     *
     * @return the value of t_organization.APPLY_DATE
     *
     * @mbg.generated
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.APPLY_DATE
     *
     * @param applyDate the value for t_organization.APPLY_DATE
     *
     * @mbg.generated
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.AUDIT_BY
     *
     * @return the value of t_organization.AUDIT_BY
     *
     * @mbg.generated
     */
    public Long getAuditBy() {
        return auditBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.AUDIT_BY
     *
     * @param auditBy the value for t_organization.AUDIT_BY
     *
     * @mbg.generated
     */
    public void setAuditBy(Long auditBy) {
        this.auditBy = auditBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.AUDIT_DATE
     *
     * @return the value of t_organization.AUDIT_DATE
     *
     * @mbg.generated
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.AUDIT_DATE
     *
     * @param auditDate the value for t_organization.AUDIT_DATE
     *
     * @mbg.generated
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.STATUS
     *
     * @return the value of t_organization.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.STATUS
     *
     * @param status the value for t_organization.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.REMARK
     *
     * @return the value of t_organization.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.REMARK
     *
     * @param remark the value for t_organization.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.CREATE_BY
     *
     * @return the value of t_organization.CREATE_BY
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.CREATE_BY
     *
     * @param createBy the value for t_organization.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.CREATE_DATE
     *
     * @return the value of t_organization.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.CREATE_DATE
     *
     * @param createDate the value for t_organization.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.CREATE_PLATFORM
     *
     * @return the value of t_organization.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_organization.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.CREATE_VERSION
     *
     * @return the value of t_organization.CREATE_VERSION
     *
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.CREATE_VERSION
     *
     * @param createVersion the value for t_organization.CREATE_VERSION
     *
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.UPDATE_BY
     *
     * @return the value of t_organization.UPDATE_BY
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.UPDATE_BY
     *
     * @param updateBy the value for t_organization.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.UPDATE_DATE
     *
     * @return the value of t_organization.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.UPDATE_DATE
     *
     * @param updateDate the value for t_organization.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.UPDATE_PLATFORM
     *
     * @return the value of t_organization.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getUpdatePlatform() {
        return updatePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.UPDATE_PLATFORM
     *
     * @param updatePlatform the value for t_organization.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setUpdatePlatform(String updatePlatform) {
        this.updatePlatform = updatePlatform == null ? null : updatePlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.UPDATE_VERSION
     *
     * @return the value of t_organization.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.UPDATE_VERSION
     *
     * @param updateVersion the value for t_organization.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }

    public String getStatusLabel() {
        return statusLabel;
    }

    public void setStatusLabel(String statusLabel) {
        this.statusLabel = statusLabel;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public String getIsCreateSchool() {
        return isCreateSchool;
    }

    public void setIsCreateSchool(String isCreateSchool) {
        this.isCreateSchool = isCreateSchool;
    }

    public String getAuditName() {
        return auditName;
    }

    public void setAuditName(String auditName) {
        this.auditName = auditName;
    }

    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }

    public String getUpdateName() {
        return updateName;
    }

    public void setUpdateName(String updateName) {
        this.updateName = updateName;
    }

    public MultipartFile getFileOrgLogo() {
        return fileOrgLogo;
    }

    public void setFileOrgLogo(MultipartFile fileOrgLogo) {
        this.fileOrgLogo = fileOrgLogo;
    }

    public Boolean getDelImage() {
        return delImage;
    }

    public void setDelImage(Boolean delImage) {
        this.delImage = delImage;
    }
}