package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;

public class RoleFunctionKey extends Columns {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rolefunction.ROLE_ID
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rolefunction.FUNCTION_CODE
     *
     * @mbg.generated
     */
    private String functionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rolefunction.ROLE_ID
     *
     * @return the value of t_rolefunction.ROLE_ID
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rolefunction.ROLE_ID
     *
     * @param roleId the value for t_rolefunction.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rolefunction.FUNCTION_CODE
     *
     * @return the value of t_rolefunction.FUNCTION_CODE
     *
     * @mbg.generated
     */
    public String getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rolefunction.FUNCTION_CODE
     *
     * @param functionCode the value for t_rolefunction.FUNCTION_CODE
     *
     * @mbg.generated
     */
    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode == null ? null : functionCode.trim();
    }
}