package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;

import java.util.Date;

public class Role extends Columns{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.ROLE_ID
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.ROLE_NAME
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.ROLE_DESC
     *
     * @mbg.generated
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.IS_ENABLE
     *
     * @mbg.generated
     */
    private String isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.ROLE_TYPE
     *
     * @mbg.generated
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.UPDATE_BY
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    private String updatePlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.UPDATE_VERSION
     *
     * @mbg.generated
     */
    private String updateVersion;

    private String createByName;
    private String updateByName;
    private String isEnableLabel;
    private String roleTypeLabel;

    public String getRoleTypeLabel() {
        return roleTypeLabel;
    }

    public void setRoleTypeLabel(String roleTypeLabel) {
        this.roleTypeLabel = roleTypeLabel;
    }

    public String getCreateByName() {
        return createByName;
    }

    public void setCreateByName(String createByName) {
        this.createByName = createByName;
    }

    public String getUpdateByName() {
        return updateByName;
    }

    public void setUpdateByName(String updateByName) {
        this.updateByName = updateByName;
    }

    public String getIsEnableLabel() {
        return isEnableLabel;
    }

    public void setIsEnableLabel(String isEnableLabel) {
        this.isEnableLabel = isEnableLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.ROLE_ID
     *
     * @return the value of t_role.ROLE_ID
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.ROLE_ID
     *
     * @param roleId the value for t_role.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.ROLE_NAME
     *
     * @return the value of t_role.ROLE_NAME
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.ROLE_NAME
     *
     * @param roleName the value for t_role.ROLE_NAME
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.ROLE_DESC
     *
     * @return the value of t_role.ROLE_DESC
     *
     * @mbg.generated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.ROLE_DESC
     *
     * @param roleDesc the value for t_role.ROLE_DESC
     *
     * @mbg.generated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.IS_ENABLE
     *
     * @return the value of t_role.IS_ENABLE
     *
     * @mbg.generated
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.IS_ENABLE
     *
     * @param isEnable the value for t_role.IS_ENABLE
     *
     * @mbg.generated
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.ROLE_TYPE
     *
     * @return the value of t_role.ROLE_TYPE
     *
     * @mbg.generated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.ROLE_TYPE
     *
     * @param roleType the value for t_role.ROLE_TYPE
     *
     * @mbg.generated
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.CREATE_BY
     *
     * @return the value of t_role.CREATE_BY
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.CREATE_BY
     *
     * @param createBy the value for t_role.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.CREATE_DATE
     *
     * @return the value of t_role.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.CREATE_DATE
     *
     * @param createDate the value for t_role.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.CREATE_PLATFORM
     *
     * @return the value of t_role.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_role.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.CREATE_VERSION
     *
     * @return the value of t_role.CREATE_VERSION
     *
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.CREATE_VERSION
     *
     * @param createVersion the value for t_role.CREATE_VERSION
     *
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.UPDATE_BY
     *
     * @return the value of t_role.UPDATE_BY
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.UPDATE_BY
     *
     * @param updateBy the value for t_role.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.UPDATE_DATE
     *
     * @return the value of t_role.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.UPDATE_DATE
     *
     * @param updateDate the value for t_role.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.UPDATE_PLATFORM
     *
     * @return the value of t_role.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getUpdatePlatform() {
        return updatePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.UPDATE_PLATFORM
     *
     * @param updatePlatform the value for t_role.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setUpdatePlatform(String updatePlatform) {
        this.updatePlatform = updatePlatform == null ? null : updatePlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.UPDATE_VERSION
     *
     * @return the value of t_role.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.UPDATE_VERSION
     *
     * @param updateVersion the value for t_role.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }
}