package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;

import java.io.Serializable;
import java.util.Date;

public class School extends Columns implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.SCHOOL_ID
     *
     * @mbg.generated
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.ORG_ID
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.SCHOOL_NAME
     *
     * @mbg.generated
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.SCHOOL_ADDRESS
     *
     * @mbg.generated
     */
    private String schoolAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.SCHOOL_CONTACT
     *
     * @mbg.generated
     */
    private String schoolContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.SCHOOL_TEL
     *
     * @mbg.generated
     */
    private String schoolTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.SCHOOL_WEBSITE
     *
     * @mbg.generated
     */
    private String schoolWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.UPDATE_BY
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    private String updatePlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.UPDATE_VERSION
     *
     * @mbg.generated
     */
    private String updateVersion;

    /**
     * 所属机构名称
     */
    private String orgName;
    /**
     * 所属机构简称
     */
    private String orgAbbrname;
    /**
     * 创建人
     */
    private String createName;
    /**
     * 修改人
     */
    private String updateName;
    /**
     * 在校学生数量
     */
    private Long studentCount;
    /**
     * 班级数量
     */
    private Long classCount;
    /**
     * 未入班学生
     */
    private Long unenrolledStudentCount;

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgAbbrname() {
        return orgAbbrname;
    }

    public void setOrgAbbrname(String orgAbbrname) {
        this.orgAbbrname = orgAbbrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.SCHOOL_ID
     *
     * @return the value of t_school.SCHOOL_ID
     *
     * @mbg.generated
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.SCHOOL_ID
     *
     * @param schoolId the value for t_school.SCHOOL_ID
     *
     * @mbg.generated
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.ORG_ID
     *
     * @return the value of t_school.ORG_ID
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.ORG_ID
     *
     * @param orgId the value for t_school.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.SCHOOL_NAME
     *
     * @return the value of t_school.SCHOOL_NAME
     *
     * @mbg.generated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.SCHOOL_NAME
     *
     * @param schoolName the value for t_school.SCHOOL_NAME
     *
     * @mbg.generated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.SCHOOL_ADDRESS
     *
     * @return the value of t_school.SCHOOL_ADDRESS
     *
     * @mbg.generated
     */
    public String getSchoolAddress() {
        return schoolAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.SCHOOL_ADDRESS
     *
     * @param schoolAddress the value for t_school.SCHOOL_ADDRESS
     *
     * @mbg.generated
     */
    public void setSchoolAddress(String schoolAddress) {
        this.schoolAddress = schoolAddress == null ? null : schoolAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.SCHOOL_CONTACT
     *
     * @return the value of t_school.SCHOOL_CONTACT
     *
     * @mbg.generated
     */
    public String getSchoolContact() {
        return schoolContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.SCHOOL_CONTACT
     *
     * @param schoolContact the value for t_school.SCHOOL_CONTACT
     *
     * @mbg.generated
     */
    public void setSchoolContact(String schoolContact) {
        this.schoolContact = schoolContact == null ? null : schoolContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.SCHOOL_TEL
     *
     * @return the value of t_school.SCHOOL_TEL
     *
     * @mbg.generated
     */
    public String getSchoolTel() {
        return schoolTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.SCHOOL_TEL
     *
     * @param schoolTel the value for t_school.SCHOOL_TEL
     *
     * @mbg.generated
     */
    public void setSchoolTel(String schoolTel) {
        this.schoolTel = schoolTel == null ? null : schoolTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.SCHOOL_WEBSITE
     *
     * @return the value of t_school.SCHOOL_WEBSITE
     *
     * @mbg.generated
     */
    public String getSchoolWebsite() {
        return schoolWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.SCHOOL_WEBSITE
     *
     * @param schoolWebsite the value for t_school.SCHOOL_WEBSITE
     *
     * @mbg.generated
     */
    public void setSchoolWebsite(String schoolWebsite) {
        this.schoolWebsite = schoolWebsite == null ? null : schoolWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.REMARK
     *
     * @return the value of t_school.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.REMARK
     *
     * @param remark the value for t_school.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.CREATE_BY
     *
     * @return the value of t_school.CREATE_BY
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.CREATE_BY
     *
     * @param createBy the value for t_school.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.CREATE_DATE
     *
     * @return the value of t_school.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.CREATE_DATE
     *
     * @param createDate the value for t_school.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.CREATE_PLATFORM
     *
     * @return the value of t_school.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_school.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.CREATE_VERSION
     *
     * @return the value of t_school.CREATE_VERSION
     *
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.CREATE_VERSION
     *
     * @param createVersion the value for t_school.CREATE_VERSION
     *
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.UPDATE_BY
     *
     * @return the value of t_school.UPDATE_BY
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.UPDATE_BY
     *
     * @param updateBy the value for t_school.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.UPDATE_DATE
     *
     * @return the value of t_school.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.UPDATE_DATE
     *
     * @param updateDate the value for t_school.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.UPDATE_PLATFORM
     *
     * @return the value of t_school.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getUpdatePlatform() {
        return updatePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.UPDATE_PLATFORM
     *
     * @param updatePlatform the value for t_school.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setUpdatePlatform(String updatePlatform) {
        this.updatePlatform = updatePlatform == null ? null : updatePlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.UPDATE_VERSION
     *
     * @return the value of t_school.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.UPDATE_VERSION
     *
     * @param updateVersion the value for t_school.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }

    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }

    public String getUpdateName() {
        return updateName;
    }

    public void setUpdateName(String updateName) {
        this.updateName = updateName;
    }

    public Long getStudentCount() {
        return studentCount;
    }

    public void setStudentCount(Long studentCount) {
        this.studentCount = studentCount;
    }

    public Long getClassCount() {
        return classCount;
    }

    public void setClassCount(Long classCount) {
        this.classCount = classCount;
    }

    public Long getUnenrolledStudentCount() {
        return unenrolledStudentCount;
    }

    public void setUnenrolledStudentCount(Long unenrolledStudentCount) {
        this.unenrolledStudentCount = unenrolledStudentCount;
    }
}