package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;

import java.io.Serializable;
import java.util.Date;

public class Student extends Columns implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.STUDENT_ID
     *
     * @mbg.generated
     */
    private Long[] studentIds;
    private Long[] userIds;
    private Long[] currentCardIds;

    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.USER_ID
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.ORG_ID
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.SCHOOL_ID
     *
     * @mbg.generated
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.SCORE
     *
     * @mbg.generated
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.DAN
     *
     * @mbg.generated
     */
    private Integer dan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.FIRST_ACTIVATE_DATE
     *
     * @mbg.generated
     */
    private Date firstActivateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.CURRENT_CARD_ID
     *
     * @mbg.generated
     */
    private Long currentCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.CURRENT_ACTIVAT_DATE
     *
     * @mbg.generated
     */
    private Date currentActivatDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.VALID_DATE
     *
     * @mbg.generated
     */
    private Date validDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.UPDATE_BY
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    private String updatePlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.UPDATE_VERSION
     *
     * @mbg.generated
     */
    private String updateVersion;

    /*状态值对应的value*/
    private String statusValue;
    /*用户账号*/
    private String ifkCode;
    /*用户姓名*/
    private String userName;
    /*所属机构名称*/
    private String orgName;
    /*所属机构简称*/
    private String orgAbbrname;
    /*所属学校名称*/
    private String schoolName;
    /*段位*/
    private  String gradeName;

    private String mobile;

    private String gender;

    private String idCard;


    private String genderName;

    private String isenableName;

    private String isEnable;
    private String email;
    private String remark;
    private String birthday;
    private String danName;
    private String cardNo;

    private String userType;
    private String photo;
    private String signature;

    public String getCardNo() {
        return cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    public String getDanName() {
        return danName;
    }

    public void setDanName(String danName) {
        this.danName = danName;
    }

    public Long[] getStudentIds() {
        return studentIds;
    }

    public void setStudentIds(Long[] studentIds) {
        this.studentIds = studentIds;
    }

    public Long[] getUserIds() {
        return userIds;
    }

    public void setUserIds(Long[] userIds) {
        this.userIds = userIds;
    }

    public Long[] getCurrentCardIds() {
        return currentCardIds;
    }

    public void setCurrentCardIds(Long[] currentCardIds) {
        this.currentCardIds = currentCardIds;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getIsEnable() {
        return isEnable;
    }

    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    public String getIsenableName() {
        return isenableName;
    }

    public void setIsenableName(String isenableName) {
        this.isenableName = isenableName;
    }

    public String getGenderName() {
        return genderName;
    }

    public void setGenderName(String genderName) {
        this.genderName = genderName;
    }

    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }
    public String getGender() {
        return gender;
    }
    public String getMobile() {
        return mobile;
    }
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }
    public String getStatusValue() {
        return statusValue;
    }

    public void setStatusValue(String statusValue) {
        this.statusValue = statusValue;
    }

    public String getIfkCode() {
        return ifkCode;
    }

    public void setIfkCode(String ifkCode) {
        this.ifkCode = ifkCode;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getOrgAbbrname() {
        return orgAbbrname;
    }

    public void setOrgAbbrname(String orgAbbrname) {
        this.orgAbbrname = orgAbbrname;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.STUDENT_ID
     *
     * @return the value of t_student.STUDENT_ID
     *
     * @mbg.generated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.STUDENT_ID
     *
     * @param studentId the value for t_student.STUDENT_ID
     *
     * @mbg.generated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.USER_ID
     *
     * @return the value of t_student.USER_ID
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.USER_ID
     *
     * @param userId the value for t_student.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.ORG_ID
     *
     * @return the value of t_student.ORG_ID
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.ORG_ID
     *
     * @param orgId the value for t_student.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.SCHOOL_ID
     *
     * @return the value of t_student.SCHOOL_ID
     *
     * @mbg.generated
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.SCHOOL_ID
     *
     * @param schoolId the value for t_student.SCHOOL_ID
     *
     * @mbg.generated
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.SCORE
     *
     * @return the value of t_student.SCORE
     *
     * @mbg.generated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.SCORE
     *
     * @param score the value for t_student.SCORE
     *
     * @mbg.generated
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.DAN
     *
     * @return the value of t_student.DAN
     *
     * @mbg.generated
     */
    public Integer getDan() {
        return dan;
    }

    public void setDan(Integer dan) {
        this.dan = dan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.FIRST_ACTIVATE_DATE
     *
     * @return the value of t_student.FIRST_ACTIVATE_DATE
     *
     * @mbg.generated
     */
    public Date getFirstActivateDate() {
        return firstActivateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.FIRST_ACTIVATE_DATE
     *
     * @param firstActivateDate the value for t_student.FIRST_ACTIVATE_DATE
     *
     * @mbg.generated
     */
    public void setFirstActivateDate(Date firstActivateDate) {
        this.firstActivateDate = firstActivateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.CURRENT_CARD_ID
     *
     * @return the value of t_student.CURRENT_CARD_ID
     *
     * @mbg.generated
     */
    public Long getCurrentCardId() {
        return currentCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.CURRENT_CARD_ID
     *
     * @param currentCardId the value for t_student.CURRENT_CARD_ID
     *
     * @mbg.generated
     */
    public void setCurrentCardId(Long currentCardId) {
        this.currentCardId = currentCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.CURRENT_ACTIVAT_DATE
     *
     * @return the value of t_student.CURRENT_ACTIVAT_DATE
     *
     * @mbg.generated
     */
    public Date getCurrentActivatDate() {
        return currentActivatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.CURRENT_ACTIVAT_DATE
     *
     * @param currentActivatDate the value for t_student.CURRENT_ACTIVAT_DATE
     *
     * @mbg.generated
     */
    public void setCurrentActivatDate(Date currentActivatDate) {
        this.currentActivatDate = currentActivatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.VALID_DATE
     *
     * @return the value of t_student.VALID_DATE
     *
     * @mbg.generated
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.VALID_DATE
     *
     * @param validDate the value for t_student.VALID_DATE
     *
     * @mbg.generated
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.CREATE_BY
     *
     * @return the value of t_student.CREATE_BY
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.CREATE_BY
     *
     * @param createBy the value for t_student.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.STATUS
     *
     * @return the value of t_student.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.STATUS
     *
     * @param status the value for t_student.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.CREATE_DATE
     *
     * @return the value of t_student.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.CREATE_DATE
     *
     * @param createDate the value for t_student.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.CREATE_PLATFORM
     *
     * @return the value of t_student.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_student.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.CREATE_VERSION
     *
     * @return the value of t_student.CREATE_VERSION
     *
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.CREATE_VERSION
     *
     * @param createVersion the value for t_student.CREATE_VERSION
     *
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.UPDATE_BY
     *
     * @return the value of t_student.UPDATE_BY
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.UPDATE_BY
     *
     * @param updateBy the value for t_student.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.UPDATE_DATE
     *
     * @return the value of t_student.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.UPDATE_DATE
     *
     * @param updateDate the value for t_student.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.UPDATE_PLATFORM
     *
     * @return the value of t_student.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getUpdatePlatform() {
        return updatePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.UPDATE_PLATFORM
     *
     * @param updatePlatform the value for t_student.UPDATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setUpdatePlatform(String updatePlatform) {
        this.updatePlatform = updatePlatform == null ? null : updatePlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.UPDATE_VERSION
     *
     * @return the value of t_student.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.UPDATE_VERSION
     *
     * @param updateVersion the value for t_student.UPDATE_VERSION
     *
     * @mbg.generated
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }

    @Override
    public String toString() {
        return "Student{" +
                "studentId=" + studentId +
                ", userId=" + userId +
                ", orgId=" + orgId +
                ", schoolId=" + schoolId +
                ", score=" + score +
                ", dan='" + dan + '\'' +
                ", firstActivateDate=" + firstActivateDate +
                ", currentCardId=" + currentCardId +
                ", currentActivatDate=" + currentActivatDate +
                ", validDate=" + validDate +
                ", createBy=" + createBy +
                ", status='" + status + '\'' +
                ", createDate=" + createDate +
                ", createPlatform='" + createPlatform + '\'' +
                ", createVersion='" + createVersion + '\'' +
                ", updateBy=" + updateBy +
                ", updateDate=" + updateDate +
                ", updatePlatform='" + updatePlatform + '\'' +
                ", updateVersion='" + updateVersion + '\'' +
                ", statusValue='" + statusValue + '\'' +
                ", ifkCode='" + ifkCode + '\'' +
                ", userName='" + userName + '\'' +
                ", orgName='" + orgName + '\'' +
                ", orgAbbrname='" + orgAbbrname + '\'' +
                ", schoolName='" + schoolName + '\'' +
                ", mobile='" + mobile + '\'' +
                ", gender='" + gender + '\'' +
                ", idCard='" + idCard + '\'' +
                '}';
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getGradeName() {
        return gradeName;
    }

    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }
}