package com.serviceindeed.yike.yikemo.domain;

public class TempClassify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_classify.Classify_ID
     *
     * @mbg.generated
     */
    private Long classifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_classify.Classify_Name
     *
     * @mbg.generated
     */
    private String classifyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_classify.SuperClass_ID
     *
     * @mbg.generated
     */
    private Integer superclassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_classify.ORG_ID
     *
     * @mbg.generated
     */
    private Integer orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_classify.School_ID
     *
     * @mbg.generated
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_classify.Remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_classify.Type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_classify.Classify_ID
     *
     * @return the value of t_temp_classify.Classify_ID
     *
     * @mbg.generated
     */
    public Long getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_classify.Classify_ID
     *
     * @param classifyId the value for t_temp_classify.Classify_ID
     *
     * @mbg.generated
     */
    public void setClassifyId(Long classifyId) {
        this.classifyId = classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_classify.Classify_Name
     *
     * @return the value of t_temp_classify.Classify_Name
     *
     * @mbg.generated
     */
    public String getClassifyName() {
        return classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_classify.Classify_Name
     *
     * @param classifyName the value for t_temp_classify.Classify_Name
     *
     * @mbg.generated
     */
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName == null ? null : classifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_classify.SuperClass_ID
     *
     * @return the value of t_temp_classify.SuperClass_ID
     *
     * @mbg.generated
     */
    public Integer getSuperclassId() {
        return superclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_classify.SuperClass_ID
     *
     * @param superclassId the value for t_temp_classify.SuperClass_ID
     *
     * @mbg.generated
     */
    public void setSuperclassId(Integer superclassId) {
        this.superclassId = superclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_classify.ORG_ID
     *
     * @return the value of t_temp_classify.ORG_ID
     *
     * @mbg.generated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_classify.ORG_ID
     *
     * @param orgId the value for t_temp_classify.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_classify.School_ID
     *
     * @return the value of t_temp_classify.School_ID
     *
     * @mbg.generated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_classify.School_ID
     *
     * @param schoolId the value for t_temp_classify.School_ID
     *
     * @mbg.generated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_classify.Remarks
     *
     * @return the value of t_temp_classify.Remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_classify.Remarks
     *
     * @param remarks the value for t_temp_classify.Remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_classify.Type
     *
     * @return the value of t_temp_classify.Type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_classify.Type
     *
     * @param type the value for t_temp_classify.Type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}