package com.serviceindeed.yike.yikemo.domain;

import com.serviceindeed.yike.yikemo.domain.helper.Columns;
import org.springframework.web.multipart.MultipartFile;

public class TempPraxis extends Columns {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.Praxis_ID
     *
     * @mbg.generated
     */
    private Long praxisId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.ORG_ID
     *
     * @mbg.generated
     */
    private Integer orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.School_ID
     *
     * @mbg.generated
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.KB_ID
     *
     * @mbg.generated
     */
    private Integer kbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.Classify_ID
     *
     * @mbg.generated
     */
    private Integer classifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.Sub_Classify_ID
     *
     * @mbg.generated
     */
    private Integer subClassifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.DAN
     *
     * @mbg.generated
     */
    private Integer dan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.Praxis_Name
     *
     * @mbg.generated
     */
    private String praxisName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.SGF
     *
     * @mbg.generated
     */
    private String sgf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.Praxis_Type
     *
     * @mbg.generated
     */
    private Integer praxisType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_temp_praxis.Status
     *
     * @mbg.generated
     */
    private Integer status;

    private String gradeName;
    private String classifyName;
    private String subClassifyName;

    private String orgAbbrname;
    private String orgName;
    private String schoolName;

    public String getOrgAbbrname() {
        return orgAbbrname;
    }

    public void setOrgAbbrname(String orgAbbrname) {
        this.orgAbbrname = orgAbbrname;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    public String getGradeName() {
        return gradeName;
    }

    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

    public String getClassifyName() {
        return classifyName;
    }

    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName;
    }

    public String getSubClassifyName() {
        return subClassifyName;
    }

    public void setSubClassifyName(String subClassifyName) {
        this.subClassifyName = subClassifyName;
    }

    private MultipartFile sgfFile;

    public MultipartFile getSgfFile() {
        return sgfFile;
    }

    public void setSgfFile(MultipartFile sgfFile) {
        this.sgfFile = sgfFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.Praxis_ID
     *
     * @return the value of t_temp_praxis.Praxis_ID
     *
     * @mbg.generated
     */
    public Long getPraxisId() {
        return praxisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.Praxis_ID
     *
     * @param praxisId the value for t_temp_praxis.Praxis_ID
     *
     * @mbg.generated
     */
    public void setPraxisId(Long praxisId) {
        this.praxisId = praxisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.ORG_ID
     *
     * @return the value of t_temp_praxis.ORG_ID
     *
     * @mbg.generated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.ORG_ID
     *
     * @param orgId the value for t_temp_praxis.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.School_ID
     *
     * @return the value of t_temp_praxis.School_ID
     *
     * @mbg.generated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.School_ID
     *
     * @param schoolId the value for t_temp_praxis.School_ID
     *
     * @mbg.generated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.KB_ID
     *
     * @return the value of t_temp_praxis.KB_ID
     *
     * @mbg.generated
     */
    public Integer getKbId() {
        return kbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.KB_ID
     *
     * @param kbId the value for t_temp_praxis.KB_ID
     *
     * @mbg.generated
     */
    public void setKbId(Integer kbId) {
        this.kbId = kbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.Classify_ID
     *
     * @return the value of t_temp_praxis.Classify_ID
     *
     * @mbg.generated
     */
    public Integer getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.Classify_ID
     *
     * @param classifyId the value for t_temp_praxis.Classify_ID
     *
     * @mbg.generated
     */
    public void setClassifyId(Integer classifyId) {
        this.classifyId = classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.Sub_Classify_ID
     *
     * @return the value of t_temp_praxis.Sub_Classify_ID
     *
     * @mbg.generated
     */
    public Integer getSubClassifyId() {
        return subClassifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.Sub_Classify_ID
     *
     * @param subClassifyId the value for t_temp_praxis.Sub_Classify_ID
     *
     * @mbg.generated
     */
    public void setSubClassifyId(Integer subClassifyId) {
        this.subClassifyId = subClassifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.DAN
     *
     * @return the value of t_temp_praxis.DAN
     *
     * @mbg.generated
     */
    public Integer getDan() {
        return dan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.DAN
     *
     * @param dan the value for t_temp_praxis.DAN
     *
     * @mbg.generated
     */
    public void setDan(Integer dan) {
        this.dan = dan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.Praxis_Name
     *
     * @return the value of t_temp_praxis.Praxis_Name
     *
     * @mbg.generated
     */
    public String getPraxisName() {
        return praxisName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.Praxis_Name
     *
     * @param praxisName the value for t_temp_praxis.Praxis_Name
     *
     * @mbg.generated
     */
    public void setPraxisName(String praxisName) {
        this.praxisName = praxisName == null ? null : praxisName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.remarks
     *
     * @return the value of t_temp_praxis.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.remarks
     *
     * @param remarks the value for t_temp_praxis.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.SGF
     *
     * @return the value of t_temp_praxis.SGF
     *
     * @mbg.generated
     */
    public String getSgf() {
        return sgf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.SGF
     *
     * @param sgf the value for t_temp_praxis.SGF
     *
     * @mbg.generated
     */
    public void setSgf(String sgf) {
        this.sgf = sgf == null ? null : sgf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.Praxis_Type
     *
     * @return the value of t_temp_praxis.Praxis_Type
     *
     * @mbg.generated
     */
    public Integer getPraxisType() {
        return praxisType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.Praxis_Type
     *
     * @param praxisType the value for t_temp_praxis.Praxis_Type
     *
     * @mbg.generated
     */
    public void setPraxisType(Integer praxisType) {
        this.praxisType = praxisType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_temp_praxis.Status
     *
     * @return the value of t_temp_praxis.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_temp_praxis.Status
     *
     * @param status the value for t_temp_praxis.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}