package com.serviceindeed.yike.yikemo.domain;

import java.util.Date;

public class UserFunction extends UserFunctionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userfunction.CREATE_BY
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userfunction.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userfunction.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    private String createPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userfunction.CREATE_VERSION
     *
     * @mbg.generated
     */
    private String createVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userfunction.CREATE_BY
     *
     * @return the value of t_userfunction.CREATE_BY
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userfunction.CREATE_BY
     *
     * @param createBy the value for t_userfunction.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userfunction.CREATE_DATE
     *
     * @return the value of t_userfunction.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userfunction.CREATE_DATE
     *
     * @param createDate the value for t_userfunction.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userfunction.CREATE_PLATFORM
     *
     * @return the value of t_userfunction.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public String getCreatePlatform() {
        return createPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userfunction.CREATE_PLATFORM
     *
     * @param createPlatform the value for t_userfunction.CREATE_PLATFORM
     *
     * @mbg.generated
     */
    public void setCreatePlatform(String createPlatform) {
        this.createPlatform = createPlatform == null ? null : createPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userfunction.CREATE_VERSION
     *
     * @return the value of t_userfunction.CREATE_VERSION
     *
     * @mbg.generated
     */
    public String getCreateVersion() {
        return createVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userfunction.CREATE_VERSION
     *
     * @param createVersion the value for t_userfunction.CREATE_VERSION
     *
     * @mbg.generated
     */
    public void setCreateVersion(String createVersion) {
        this.createVersion = createVersion == null ? null : createVersion.trim();
    }
}