package com.serviceindeed.yike.yikemo.domain;

public class UserFunctionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userfunction.USER_ID
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userfunction.FUNCTION_CODE
     *
     * @mbg.generated
     */
    private String functionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userfunction.USER_ID
     *
     * @return the value of t_userfunction.USER_ID
     *
     * @mbg.generated
     */

    private String[] functionCodes;

    public String[] getFunctionCodes() {
        return functionCodes;
    }

    public void setFunctionCodes(String[] functionCodes) {
        this.functionCodes = functionCodes;
    }


    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userfunction.USER_ID
     *
     * @param userId the value for t_userfunction.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userfunction.FUNCTION_CODE
     *
     * @return the value of t_userfunction.FUNCTION_CODE
     *
     * @mbg.generated
     */
    public String getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userfunction.FUNCTION_CODE
     *
     * @param functionCode the value for t_userfunction.FUNCTION_CODE
     *
     * @mbg.generated
     */
    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode == null ? null : functionCode.trim();
    }
}